//
//  NSString_BibleMurder.h
//  Promote Murder
//

#import <Foundation/Foundation.h>

@interface NSString (BibleMurder)

+ (NSString*) stringByTakingARandomPassageFromTheBibleThatPromotesMurder;

@end

@implementation NSString (BibleMurder)

NSArray* murderQuotes;

+ (NSString*) stringByTakingARandomPassageFromTheBibleThatPromotesMurder
{
    if(murderQuotes == nil)
    {
        murderQuotes = [NSArray arrayWithObjects:
                        @"Anyone arrogant enough to reject the verdict of the judge or of the priest who represents the LORD your God must be put to death. Such evil must be purged from Israel.",
                        @"You should not let a sorceress live.",
                        @"If a man lies with a male as with a women, both of them shall be put to death for their abominable deed; they have forfeited their lives.",
                        @"A man or a woman who acts as a medium or fortuneteller shall be put to death by stoning; they have no one but themselves to blame for their death.",
                        @"Whoever strikes his father or mother shall be put to death.",
                        @"If one curses his father or mother, his lamp will go out at the coming of darkness.",
                        @"All who curse their father or mother must be put to death. They are guilty of a capital offense.",
                        @"If a man commits adultery with another man's wife, both the man and the woman must be put to death.",
                        @"A priest's daughter who loses her honor by committing fornication and thereby dishonors her father also, shall be burned to death.",
                        @"Whoever sacrifices to any god, except the Lord alone, shall be doomed.",
                        @"They entered into a covenant to seek the Lord, the God of their fathers, with all their heart and soul; and everyone who would not seek the Lord, the God of Israel, was to be put to death, whether small or great, whether man or woman.",
                        @"If a man still prophesies, his parents, father and mother, shall say to him, \"You shall not live, because you have spoken a lie in the name of the Lord.\" When he prophesies, his parents, father and mother, shall thrust him through.",
                        @"Suppose you hear in one of the towns the LORD your God is giving you that some worthless rabble among you have led their fellow citizens astray by encouraging them to worship foreign gods. In such cases, you must examine the facts carefully. If you find it is true and can prove that such a detestable act has occurred among you, you must attack that town and completely destroy all its inhabitants, as well as all the livestock. Then you must pile all the plunder in the middle of the street and burn it. Put the entire town to the torch as a burnt offering to the LORD your God. That town must remain a ruin forever; it may never be rebuilt. Keep none of the plunder that has been set apart for destruction. Then the LORD will turn from his fierce anger and be merciful to you. He will have compassion on you and make you a great nation, just as he solemnly promised your ancestors. \"The LORD your God will be merciful only if you obey him and keep all the commands I am giving you today, doing what is pleasing to him.\"",
                        @"But if this charge is true, and evidence of the girls virginity is not found, they shall bring the girl to the entrance of her fathers house and there her townsman shall stone her to death, because she committed a crime against Israel by her unchasteness in her father's house. Thus shall you purge the evil from your midst.",
                        @"Suppose a man or woman among you, in one of your towns that the LORD your God is giving you, has done evil in the sight of the LORD your God and has violated the covenant by serving other gods or by worshiping the sun, the moon, or any of the forces of heaven, which I have strictly forbidden. When you hear about it, investigate the matter thoroughly. If it is true that this detestable thing has been done in Israel, then that man or woman must be taken to the gates of the town and stoned to death.",
                        @"One day a man who had an Israelite mother and an Egyptian father got into a fight with one of the Israelite men. During the fight, this son of an Israelite woman blasphemed the LORD's name. So the man was brought to Moses for judgment. His mother's name was Shelomith. She was the daughter of Dibri of the tribe of Dan. They put the man in custody until the LORD's will in the matter should become clear. Then the LORD said to Moses, \"Take the blasphemer outside the camp, and tell all those who heard him to lay their hands on his head. Then let the entire community stone him to death. Say to the people of Israel: Those who blaspheme God will suffer the consequences of their guilt and be punished. Anyone who blasphemes the LORD's name must be stoned to death by the whole community of Israel. Any Israelite or foreigner among you who blasphemes the LORD's name will surely die.\"",
                        @"Suppose there are prophets among you, or those who have dreams about the future, and they promise you signs or miracles, and the predicted signs or miracles take place. If the prophets then say, 'Come, let us worship the gods of foreign nations,' do not listen to them. The LORD your God is testing you to see if you love him with all your heart and soul. Serve only the LORD your God and fear him alone. Obey his commands, listen to his voice, and cling to him. The false prophets or dreamers who try to lead you astray must be put to death, for they encourage rebellion against the LORD your God, who brought you out of slavery in the land of Egypt. Since they try to keep you from following the LORD your God, you must execute them to remove the evil from among you.",
                        @"But any prophet who claims to give a message from another god or who falsely claims to speak for me must die.' You may wonder, 'How will we know whether the prophecy is from the LORD or not?' If the prophet predicts something in the LORD's name and it does not happen, the LORD did not give the message. That prophet has spoken on his own and need not be feared.",
                        @"So God let them go ahead and do whatever shameful things their hearts desired. As a result, they did vile and degrading things with each other's bodies. Instead of believing what they knew was the truth about God, they deliberately chose to believe lies. So they worshiped the things God made but not the Creator himself, who is to be praised forever. Amen. That is why God abandoned them to their shameful desires. Even the women turned against the natural way to have sex and instead indulged in sex with each other. And the men, instead of having normal sexual relationships with women, burned with lust for each other. Men did shameful things with other men and, as a result, suffered within themselves the penalty they so richly deserved. When they refused to acknowledge God, he abandoned them to their evil minds and let them do things that should never be done. Their lives became full of every kind of wickedness, sin, greed, hate, envy, murder, fighting, deception, malicious behavior, and gossip. They are backstabbers, haters of God, insolent, proud, and boastful. They are forever inventing new ways of sinning and are disobedient to their parents. They refuse to understand, break their promises, and are heartless and unforgiving. They are fully aware of God's death penalty for those who do these things, yet they go right ahead and do them anyway. And, worse yet, they encourage others to do them, too.",
                        @"For the LORD had said to Moses, 'Exempt the tribe of Levi from the census; do not include them when you count the rest of the Israelites. You must put the Levites in charge of the Tabernacle of the Covenant, along with its furnishings and equipment. They must carry the Tabernacle and its equipment as you travel, and they must care for it and camp around it. Whenever the Tabernacle is moved, the Levites will take it down and set it up again. Anyone else who goes too near the Tabernacle will be executed.'",
                        @"The LORD then gave these further instructions to Moses: 'Tell the people of Israel to keep my Sabbath day, for the Sabbath is a sign of the covenant between me and you forever. It helps you to remember that I am the LORD, who makes you holy. Yes, keep the Sabbath day, for it is holy. Anyone who desecrates it must die; anyone who works on that day will be cut off from the community. Work six days only, but the seventh day must be a day of total rest. I repeat: Because the LORD considers it a holy day, anyone who works on the Sabbath must be put to death.'",
                        @"From there Elisha went up to Bethel. While he was on his way, some small boys came out of the city and jeered at him. \"Go up baldhead,\" they shouted, \"go up baldhead!\" The prophet turned and saw them, and he cursed them in the name of the Lord. Then two shebears came out of the woods and tore forty two of the children to pieces.",
                        @"And he smote of the men of Beth-shemesh, because they had looked into the ark of Jehovah, he smote of the people seventy men, 'and' fifty thousand men; and the people mourned, because Jehovah had smitten the people with a great slaughter. And the men of Beth-shemesh said, Who is able to stand before Jehovah, this holy God? and to whom shall he go up from us?",
                        @"Meanwhile, the LORD instructed one of the group of prophets to say to another man, \"Strike me!\" But the man refused to strike the prophet. Then the prophet told him, \"Because you have not obeyed the voice of the LORD, a lion will kill you as soon as you leave me.\" And sure enough, when he had gone, a lion attacked and killed him.",
                        @"The ark of God was placed on a new cart and taken away from the house of Abinadab on the hill. Uzzah and Ahio, sons of Abinadab guided the cart, with Ahio walking before it, while David and all the Israelites made merry before the Lord with all their strength, with singing and with citharas, harps, tambourines, sistrums, and cymbals.",
                        @"When they came to the threshing floor of Nodan, Uzzah reached out his hand to the ark of God to steady it, for the oxen were making it tip. But the Lord was angry with Uzzah; God struck him on that spot, and he died there before God.",
                        @"Make ready to slaughter his sons for the guilt of their fathers; Lest they rise and posses the earth, and fill the breadth of the world with tyrants.",
                        @"The glory of Israel will fly away like a bird, for your children will die at birth or perish in the womb or never even be conceived. Even if your children do survive to grow up, I will take them from you. It will be a terrible day when I turn away and leave you alone. I have watched Israel become as beautiful and pleasant as Tyre. But now Israel will bring out her children to be slaughtered.\" O LORD, what should I request for your people? I will ask for wombs that don't give birth and breasts that give no milk. The LORD says, \"All their wickedness began at Gilgal; there I began to hate them. I will drive them from my land because of their evil actions. I will love them no more because all their leaders are rebels. The people of Israel are stricken. Their roots are dried up; they will bear no more fruit. And if they give birth, I will slaughter their beloved children.\"",
                        @"\"Then I heard the LORD say to the other men, \"Follow him through the city and kill everyone whose forehead is not marked. Show no mercy; have no pity! Kill them all old and young, girls and women and little children. But do not touch anyone with the mark. Begin your task right here at the Temple.\" So they began by killing the seventy leaders. \"Defile the Temple!\" the LORD commanded. \"Fill its courtyards with the bodies of those you kill! Go!\" So they went throughout the city and did as they were told.\"",
                        @"And at midnight the LORD killed all the firstborn sons in the land of Egypt, from the firstborn son of Pharaoh, who sat on the throne, to the firstborn son of the captive in the dungeon. Even the firstborn of their livestock were killed. Pharaoh and his officials and all the people of Egypt woke up during the night, and loud wailing was heard throughout the land of Egypt. There was not a single house where someone had not died.",
                        @"\"You are my battle-ax and sword,\" says the LORD. \"With you I will shatter nations and destroy many kingdoms. With you I will shatter armies, destroying the horse and rider, the chariot and charioteer. With you I will shatter men and women, old people and children, young men and maidens. With you I will shatter shepherds and flocks, farmers and oxen, captains and rulers. \"As you watch, I will repay Babylon and the people of Babylonia for all the wrong they have done to my people in Jerusalem,\" says the LORD. \"Look, O mighty mountain, destroyer of the earth! I am your enemy,\" says the LORD. \"I will raise my fist against you, to roll you down from the heights. When I am finished, you will be nothing but a heap of rubble. You will be desolate forever. Even your stones will never again be used for building. You will be completely wiped out,\" says the LORD.",
                        @"If even then you remain hostile toward me and refuse to obey, I will inflict you with seven more disasters for your sins. I will release wild animals that will kill your children and destroy your cattle, so your numbers will dwindle and your roads will be deserted.",
                        @"Anyone who is captured will be run through with a sword. Their little children will be dashed to death right before their eyes. Their homes will be sacked and their wives raped by the attacking hordes. For I will stir up the Medes against Babylon, and no amount of silver or gold will buy them off. The attacking armies will shoot down the young people with arrows. They will have no mercy on helpless babies and will show no compassion for the children.",
                        @"When he reached Lehi, and the Philistines came shouting to meet him, the spirit of the Lord came upon him: the ropes around his arms become as flax that is consumed by fire and the bonds melted away from his hands. Near him was the fresh jawbone of an ass; he reached out, grasped it, and with it killed a thousand men.",
                        @"There was also a man named Ananias who, with his wife, Sapphira, sold some property. He brought part of the money to the apostles, but he claimed it was the full amount. His wife had agreed to this deception. Then Peter said, \"Ananias, why has Satan filled your heart? You lied to the Holy Spirit, and you kept some of the money for yourself. The property was yours to sell or not sell, as you wished. And after selling it, the money was yours to give away. How could you do a thing like this? You weren't lying to us but to God.\" As soon as Ananias heard these words, he fell to the floor and died. Everyone who heard about it was terrified. Then some young men wrapped him in a sheet and took him out and buried him. About three hours later his wife came in, not knowing what had happened. Peter asked her, \"Was this the price you and your husband received for your land?\" \"Yes,\" she replied, \"that was the price.\" And Peter said, \"How could the two of you even think of doing a thing like this conspiring together to test the Spirit of the Lord? Just outside that door are the young men who buried your husband, and they will carry you out, too.\" Instantly, she fell to the floor and died. When the young men came in and saw that she was dead, they carried her out and buried her beside her husband. Great fear gripped the entire church and all others who heard what had happened.",
                        @"This is what the Lord of hosts has to say: 'I will punish what Amalek did to Israel when he barred his way as he was coming up from Egypt. Go, now, attack Amalek, and deal with him and all that he has under the ban. Do not spare him, but kill men and women, children and infants, oxen and sheep, camels and asses.'",
                        @"Cursed be he who does the Lords work remissly, cursed he who holds back his sword from blood.",
                        @"But the territory of the Danites was too small for them; so the Danites marched up and attacked Leshem, which they captured and put to the sword. Once they had taken possession of Lesham, they renamed the settlement after their ancestor Dan.",
                        @"Then the LORD said to me, \"Even if Moses and Samuel stood before me pleading for these people, I wouldn't help them. Away with them! Get them out of my sight! And if they say to you, 'But where can we go?' tell them, 'This is what the LORD says: Those who are destined for death, to death; those who are destined for war, to war; those who are destined for famine, to famine; those who are destined for captivity, to captivity.' \"I will send four kinds of destroyers against them,\" says the LORD. \"I will send the sword to kill, the dogs to drag away, the vultures to devour, and the wild animals to finish up what is left. Because of the wicked things Manasseh son of Hezekiah, king of Judah, did in Jerusalem, I will make my people an object of horror to all the kingdoms of the earth.\"",
                        @"I will make Mount Seir utterly desolate, killing off all who try to escape and any who return. I will fill your mountains with the dead. Your hills, your valleys, and your streams will be filled with people slaughtered by the sword. I will make you desolate forever. Your cities will never be rebuilt. Then you will know that I am the LORD.",
                        @"My angel will go before you and bring you to the Amorites, Hittites, Perizzites, Canaanites, Hivites, and Jebusites; and I will wipe them out.",
                        @"Then the LORD said to Joshua, \"Do not be afraid or discouraged. Take the entire army and attack Ai, for I have given to you the king of Ai, his people, his city, and his land. You will destroy them as you destroyed Jericho and its king. But this time you may keep the captured goods and the cattle for yourselves. Set an ambush behind the city.\" So Joshua and the army of Israel set out to attack Ai. Joshua chose thirty thousand fighting men and sent them out at night with these orders: \"Hide in ambush close behind the city and be ready for action. When our main army attacks, the men of Ai will come out to fight as they did before, and we will run away from them. We will let them chase us until they have all left the city. For they will say, 'The Israelites are running away from us as they did before.' Then you will jump up from your ambush and take possession of the city, for the LORD your God will give it to you. Set the city on fire, as the LORD has commanded. You have your orders.\" So they left that night and lay in ambush between Bethel and the west side of Ai. But Joshua remained among the people in the camp that night.",
                        @"Early the next morning Joshua roused his men and started toward Ai, accompanied by the leaders of Israel. They camped on the north side of Ai, with a valley between them and the city. That night Joshua sent five thousand men to lie in ambush between Bethel and Ai, on the west side of the city. So they stationed the main army north of the city and the ambush west of the city. Joshua himself spent that night in the valley. When the king of Ai saw the Israelites across the valley, he and all his army hurriedly went out early the next morning and attacked the Israelites at a place overlooking the Jordan Valley. But he didn't realize there was an ambush behind the city. Joshua and the Israelite army fled toward the wilderness as though they were badly beaten, and all the men in the city were called out to chase after them. In this way, they were lured away from the city. There was not a man left in Ai or Bethel who did not chase after the Israelites, and the city was left wide open.",
                        @"Then the LORD said to Joshua, \"Point your spear toward Ai, for I will give you the city.\" Joshua did as he was commanded. As soon as Joshua gave the signal, the men in ambush jumped up and poured into the city. They quickly captured it and set it on fire. When the men of Ai looked behind them, smoke from the city was filling the sky, and they had nowhere to go. For the Israelites who had fled in the direction of the wilderness now turned on their pursuers. When Joshua and the other Israelites saw that the ambush had succeeded and that smoke was rising from the city, they turned and attacked the men of Ai. Then the Israelites who were inside the city came out and started killing the enemy from the rear. So the men of Ai were caught in a trap, and all of them died. Not a single person survived or escaped. Only the king of Ai was taken alive and brought to Joshua.",
                        @"When the Israelite army finished killing all the men outside the city, they went back and finished off everyone inside. So the entire population of Ai was wiped out that day twelve thousand in all. For Joshua kept holding out his spear until everyone who had lived in Ai was completely destroyed. Only the cattle and the treasures of the city were not destroyed, for the Israelites kept these for themselves, as the LORD had commanded Joshua. So Ai became a permanent mound of ruins, desolate to this very day. Joshua hung the king of Ai on a tree and left him there until evening. At sunset the Israelites took down the body and threw it in front of the city gate. They piled a great heap of stones over him that can still be seen today.",
                        @"When the people heard the sound of the horns, they shouted as loud as they could. Suddenly, the walls of Jericho collapsed, and the Israelites charged straight into the city from every side and captured it. They completely destroyed everything in it men and women, young and old, cattle, sheep, donkeys everything.",
                        @"'You have done more evil than all who lived before you. You have made other gods and have made me furious with your gold calves. And since you have turned your back on me, I will bring disaster on your dynasty and kill all your sons, slave or free alike. I will burn up your royal dynasty as one burns up trash until it is all gone. I, the LORD, vow that the members of your family who die in the city will be eaten by dogs, and those who die in the field will be eaten by vultures.' Then Ahijah said to Jeroboam's wife, \"Go on home, and when you enter the city, the child will die. All Israel will mourn for him and bury him. He is the only member of your family who will have a proper burial, for this child is the only good thing that the LORD, the God of Israel, sees in the entire family of Jeroboam. And the LORD will raise up a king over Israel who will destroy the family of Jeroboam. This will happen today, even now! Then the LORD will shake Israel like a reed whipped about in a stream. He will uproot the people of Israel from this good land that he gave their ancestors and will scatter them beyond the Euphrates River, for they have angered the LORD by worshiping Asherah poles. He will abandon Israel because Jeroboam sinned and made all of Israel sin along with him.\"",
                        @"The men of Israel withdrew through the territory of the Benjaminites, putting to the sword the inhabitants of the city, the livestock, and all they chanced upon. Moreover they destroyed by fire all the cities they came upon.",
                        @"That night the angel of the Lord went forth and struck down one hundred and eighty five thousand men in the Assyrian camp. Early the next morning, there they were, all the corpuses of the dead.",
                        @"\"All of you who are on the LORD's side, come over here and join me.\" And all the Levites came. He told them, \"This is what the LORD, the God of Israel, says: Strap on your swords! Go back and forth from one end of the camp to the other, killing even your brothers, friends, and neighbors.\" The Levites obeyed Moses, and about three thousand people died that day. Then Moses told the Levites, \"Today you have been ordained for the service of the LORD, for you obeyed him even though it meant killing your own sons and brothers. Because of this, he will now give you a great blessing.\"",
                        @"And Joshua said to Achan, \"My son, give, I pray thee, glory to the LORD God of Israel, and make confession to him; and tell me now what thou hast done, hide it not from me\". And Achan answered Joshua, and said, \"Indeed I have sinned against the LORD God of Israel, and thus and thus have I done. When I saw among the spoils a goodly Babylonish garment, and two hundred shekels of silver, and a wedge of gold of fifty shekels weight, then I coveted them, and took them, and behold, they are hid in the earth in the midst of my tent, and the silver under it.\" So Joshua sent messengers, and they ran to the tent, and behold, it was hid in his tent, and the silver under it. And they took them from the midst of the tent, and brought them to Joshua, and to all the children of Israel, and laid them out before the LORD. And Joshua, and all Israel with him, took Achan the son of Zerah, and the silver, and the garment, and the wedge of gold, and his sons, and his daughters, and his oxen, and his asses, and his sheep, and his tent, and all that he had: and they brought them to the valley of Achor. And Joshua said, why hast thou troubled us? the LORD shall trouble thee this day. And all Israel stoned him with stones, and burned them with fire, after they had stoned them with stones. And they raised over him a great heap of stones to this day. So the LORD turned from the fierceness of his anger: wherefore the name of that place was called the valley of Achor to this day.",
                        @"While the Israelites were camped at Acacia, some of the men defiled themselves by sleeping with the local Moabite women. These women invited them to attend sacrifices to their gods, and soon the Israelites were feasting with them and worshiping the gods of Moab. Before long Israel was joining in the worship of Baal of Peor, causing the LORD's anger to blaze against his people. The LORD issued the following command to Moses: \"Seize all the ringleaders and execute them before the LORD in broad daylight, so his fierce anger will turn away from the people of Israel.\" So Moses ordered Israel's judges to execute everyone who had joined in worshiping Baal of Peor. Just then one of the Israelite men brought a Midianite woman into the camp, right before the eyes of Moses and all the people, as they were weeping at the entrance of the Tabernacle. When Phinehas son of Eleazar and grandson of Aaron the priest saw this, he jumped up and left the assembly. Then he took a spear and rushed after the man into his tent. Phinehas thrust the spear all the way through the man's body and into the woman's stomach. So the plague against the Israelites was stopped, but not before 24,000 people had died.",
                        @"At the customary time for offering the evening sacrifice, Elijah the prophet walked up to the altar and prayed, \"O LORD, God of Abraham, Isaac, and Jacob, prove today that you are God in Israel and that I am your servant. Prove that I have done all this at your command. O LORD, answer me! Answer me so these people will know that you, O LORD, are God and that you have brought them back to yourself.\" Immediately the fire of the LORD flashed down from heaven and burned up the young bull, the wood, the stones, and the dust. It even licked up all the water in the ditch! And when the people saw it, they fell on their faces and cried out, \"The LORD is God! The LORD is God!\" Then Elijah commanded, \"Seize all the prophets of Baal. Don't let a single one escape!\" So the people seized them all, and Elijah took them down to the Kishon Valley and killed them there.",
                        @"\"Go up, my warriors, against the land of Merathaim and against the people of Pekod. Yes, march against Babylon, the land of rebels, a land that I will judge! Pursue, kill, and completely destroy them, as I have commanded you,\" says the LORD. \"Let the battle cry be heard in the land, a shout of great destruction\".",
                        @"Then, with Micah's idols and his priest, the men of Dan came to the town of Laish, whose people were peaceful and secure. They attacked and killed all the people and burned the town to the ground. There was no one to rescue the residents of the town, for they lived a great distance from Sidon and had no allies nearby. This happened in the valley near Beth-rehob.Then the people of the tribe of Dan rebuilt the town and lived there. They renamed the town Dan after their ancestor, Israel's son, but it had originally been called Laish.",
                        nil];
    }
    
    return [murderQuotes objectAtIndex:(arc4random() % [murderQuotes count])];
}

@end